advance_level/school_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    url(r"^$", views.SchoolListView.as_view(), name="list"),
    url(r"^(?P<pk>\d+)/$", views.SchoolDetailView.as_view(), name="detail"),
    url(r"^create/$", views.SchoolCreateView.as_view(), name="create"),
    url(r"^update/(?P<pk>\d+)/$", views.SchoolUpdateView.as_view(), name="update"),
    url(r"^delete/(?P<pk>\d+)/$", views.SchoolDeleteView.as_view(), name="delete"),
]

advance_level/school_project/school_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view(),name="index"),
    url(r'^basic_app/',include("basic_app.urls",namespace="basic_app")),
]

advance_level/school_project/basic_app/models.py
from django.db import models

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    address = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=256)
    school = models.ForeignKey(School,related_name="students")
    age = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    

advance_level/school_project/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from basic_app.models import School
# Create your views here.

class IndexView(TemplateView):
    template_name = "index.html"

class SchoolListView(ListView):
    context_object_name = "schools"
    model = School

class SchoolDetailView(DetailView):
    context_object_name = "school_detail"    
    model = School
    template_name = "basic_app/school_detail.html"

advance_level/school_project/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create School</a></li>
            </ul>
        </nav>
    </div>
    <div class="container">
        {% block body_block %}
            
        {% endblock  %}
    </div>
</body>
</html>

advance_level/school_project/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <div class="container">
        <h1>Do you want to delete {{school.name}} </h1>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <p><a class="btn btn-link" href="{% url 'basic_app:detail' pk=school.pk%}">Cancel</a></p>
        </form>
    </div>
{% endblock  %}

advance_level/school_project/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <h1>Welcome to the school details page!!!!</h1>
    <div class="jumbotron">
        <h2>Here is the school detail</h2>
        <p>Name: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Address: {{school_detail.address}}</p>
        <h2>Students:</h2>
        {% for student in school_detail.students.all %}
            <p>{{student.name}} is {{student.age}} years old!! </p>
        {% endfor %}
    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    
        <p><a class="btn btn-warning" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
    </div>    


{% endblock  %}

advance_level/school_project/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    
    <div class="container">
        <h1>
        {% if not form.instance.pk %}
        create school
        {% else %}
        update school
        {% endif %}
    </h1>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
    </div>

{% endblock  %}

advance_level/school_project/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    
    <h1>Here are the list of schools!!!</h1>
    <ol>
        {% for school in schools %}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>
{% endblock  %}

advance_level/school_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create School</a></li>
            </ul>
        </nav>
    </div>
    <div class="container">
        {% block body_block %}
            
        {% endblock  %}
    </div>
</body>
</html>

advance_level/school_project/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <h1>This is the school project!!!!!!</h1>
{% endblock  %}