advance_level/demo_project/demo_app/urls.py
from django.conf.urls import url
from demo_app import views

app_name = "demo_app"

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name="detail"),
    url(r"^create/$",views.SchoolCreateView.as_view(),name="create"),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name="update"),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name="delete"),
]

advance_level/demo_project/demo_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from demo_app import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$",views.IndexView.as_view(),name='index'),
    url(r'^demo_app/', include("demo_app.urls", namespace="demo_app")),
]

advance_level/demo_project/demo_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    address = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("demo_app:detail", kwargs={"pk": self.pk})
    
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name="students")

    def __str__(self):
        return self.name
    

advance_level/demo_project/demo_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from demo_app.models import School
from django.urls import reverse_lazy
# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"


class SchoolListView(ListView):
    context_object_name = "schools"
    model = School


class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = School
    template_name = "demo_app/school_detail.html"

class SchoolCreateView(CreateView):
    model = School
    fields = ("name","principal","address")

class SchoolUpdateView(UpdateView):
    model=School
    fields = ("name","principal")

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("demo_app:list")

advance_level/demo_project/demo_app/templates/demo_app/demo_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class-="navbar-link" href="{% url 'demo_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'demo_app:create' %}">Create</a></li>
        </ul>
    </nav>
</div>
    <div class="container">
        {% block body_block %}
        
        {% endblock  %}
    </div>
</body>
</html>

advance_level/demo_project/demo_app/templates/demo_app/school_confirm_delete.html
{% extends "demo_app/demo_app_base.html" %}

{% block body_block %}
    <div class="container">
        <h1>Do you want to delete {{school.name}} </h1>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <p><a class="btn btn-link" href="{% url 'demo_app:detail' pk=school.pk%}">Cancel</a></p>
        </form>
    </div>
{% endblock  %}

advance_level/demo_project/demo_app/templates/demo_app/school_detail.html
{% extends "demo_app/demo_app_base.html" %}
{% block body_block %}
    <h1>This is details of this school!!!</h1>
        <p>School: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}} </p>
        <p>Address: {{school_detail.address}} </p>
    <h1>Here are the details of the students!!!</h1>
        {% for student in school_detail.students.all %}
            <p>{{student.name}} is {{student.age}} years old!! </p>
        {% endfor %}
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'demo_app:update' pk=school_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'demo_app:delete' pk=school_detail.pk %}">Delete</a></p>
    </div>
{% endblock  %}

advance_level/demo_project/demo_app/templates/demo_app/school_form.html
{% extends "demo_app/demo_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>
            {% if form.instance.pk %}
                Create School
            {% else %}
                Update School
            {% endif %}
        </h1>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Create">
        </form>
    </div>
{% endblock  %}

advance_level/demo_project/demo_app/templates/demo_app/school_list.html
{% extends "demo_app/demo_app_base.html" %}
{% block body_block %}
    <h1>This is the School List page!!!</h1>
    <div class="jumbotron">
        <h1>Here are the school list</h1>
        {% for school in schools %}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </div>
{% endblock  %}

advance_level/demo_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class-="navbar-link" href="{% url 'demo_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'demo_app:create' %}">Create</a></li>
        </ul>
    </nav>
</div>
    <div class="container">
        {% block body_block %}
        
        {% endblock  %}
    </div>
</body>
</html>

advance_level/demo_project/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <h1>This is the home page of the school project!!!!</h1>
{% endblock  %}