level_five/learning_user/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='basic_app'

urlpatterns = [
    url(r'^register/$',views.registrations,name='register'),
    url(r'^user_login/$',views.user_login,name="user_login"),
]

level_five/learning_user/learning_user/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout$',views.user_logout,name="logout")
]

level_five/learning_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)
    

    def __str__(self):
        return self.user.username

level_five/learning_user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ("username","email","password")

class UserProfileInfoForm(forms.ModelForm):
    
    class Meta:
        model = UserProfileInfo
        fields = ("portfolio_site","profile_pic")

level_five/learning_user/basic_app/views.py
from django.shortcuts import render
from basic_app.models import UserProfileInfo
from basic_app.forms import UserProfileForm,UserProfileInfoForm
from django.contrib.auth.models import User

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def registrations(request):

    registered = False

    if request.method=="POST":
        user_form = UserProfileForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user #this is the one to one relationship with the user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()

                registered =True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserProfileForm()
        profile_form=UserProfileInfoForm()


    return render(request,'basic_app/registrations.html',
                  {"registered": registered,"user_form": user_form,"profile_form": profile_form})

def user_login(request):

    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))

            else:
                HttpResponse("User is not active")

        else:
            print("someone tried to login but failed")
            print("username {} and password{}".format(username,password))
            return HttpResponse("Invalid Credentials")

    else:
        return render(request,'basic_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))
        

level_five/learning_user/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Base</title>
</head>
<body>
    <div class="container">
        <h1>Django</h1>
        <nav class='navbar navbar-default'>
            <a class='navbar-brand' href="{% url 'index' %}">Home</a>
            <ul class='nav navbar-nav'>
                <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class='navbar-link' href="{% url 'basic_app:register' %}">Registrations</a></li>
                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <div class="container">
        {% block body_block %}
        
        {% endblock  %}
    </div>
</body>
</html>

level_five/learning_user/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>This is the home page!!!</h1>
    <h2>Please click on the registrations link to register with us</h2>
{% endblock  %}

level_five/learning_user/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>This is the Login Page</h1>
    <div class="jumbotron">
        <h1>Please Enter Your Credentials!!!!</h1>
        <form method="POST" action="{% url 'basic_app:user_login' %}">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Please enter the username">

            <label for="password">Password</label>
            <input type="password" name="password">

            <input type="submit" class="btn btn-success" value="Login">
        </form>
    </div>

{% endblock  %}

level_five/learning_user/templates/basic_app/registrations.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="container">
        <h1>This is the registrations page!!</h1>
        <div class="jumbotron">
            {% if registered %}
                <h1>Thank you for Joining</h1>
            {% else %}
            <h1>Please Fill out the form!!</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" class='btn btn-primary' value="Register">
            </form>
            {% endif %}
        </div>
    </div>
{% endblock  %}