level_four/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^other/',views.other,name='other'),
    url(r'^relative$',views.relative,name='relative'),
]

level_four/learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^relative/',include('basic_app.urls')),
]

level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict={"text":"Hello World","number":100}
    return render(request,"basic_app/index.html", context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_page.html')

level_four/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Base</title>
</head>
<body>
    <div class='container'>
        <nav class='navbar navabr-default'>
        <ul class='nav navbar-nav'>
            <li><a class='navbar-brand' href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class='navbar-link' href="{% url 'index' %}">Index</a></li>
            <li><a class='navbar-link' href="{% url 'basic_app:other' %}">Other</a></li>
            <li><a class='navbar-link' href="{% url 'basic_app:relative' %}">Relative</a></li>
        </ul>
        </nav>
    </div>

    <div class="container">
        {% block body_block %}
        
        {% endblock  %}
    </div>
</body>
</html>

level_four/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>This is the Index Page</h1>
        <h1>{{text|cut:'Hello'}}</h1>
        <h1>{{number|add:"20"}}</h1>
    {% endblock %}

level_four/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>This is the other page!!!</h1>
{% endblock %}   

level_four/learning_templates/templates/basic_app/relative_url_page.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>This is the relative url page!!!</h1>
{% endblock  %}